# Messages
ENTER = 'ENTER'
ALLOW = 'ALLOW'
RELEASE = 'RELEASE'
TIMEOUT_STEP = 'TIMEOUT_STEP'
TIMEOUT = 'TIMEOUT'
# Process behaviors
ACTIVE = 'ACTIVE'
PASSIVE = 'PASSIVE'
BEHAVIOR_TYPES = [ACTIVE, PASSIVE]
